import type { PlanId } from '@/lib/plans';

export type ContentRating = 'SFW' | '18+';

export type AvailableGirl = {
  id: string;
  displayName: string;
  ageGroup: 'Adult 21+';
  city?: string;
  languages: string[];
  specialization: 'универсальная' | 'cosplay' | 'fitness' | 'beauty' | 'luxury' | 'business' | 'travel' | 'gaming' | 'editorial' | 'voice/persona';
  vibe: string;
  bio: string;
  strengths: [string, string, string];
  tags: string[];
  access: PlanId;
  contentRating: ContentRating;
  previewImages: [string, string, string];
  capabilities: string[];
};

export const AVAILABLE_GIRLS: AvailableGirl[] = [
  { id: 'sofia-next', displayName: 'Sofia Next', ageGroup: 'Adult 21+', city: 'Prague', languages: ['RU', 'EN'], specialization: 'универсальная', vibe: 'Тёплый lifestyle и дружелюбный tone для повседневного контента.', bio: 'Виртуальный взрослый персонаж (21+) с SFW-позиционированием. Сильна в регулярных сериях контента для широкой аудитории.', strengths: ['Сторис-серии', 'UGC-стиль', 'Повседневные образы'], tags: ['lifestyle', 'daily', 'ugc', 'cozy'], access: 'trial', contentRating: 'SFW', previewImages: ['from-rose-300/70 via-pink-400/70 to-violet-500/60', 'from-amber-200/70 via-rose-300/70 to-fuchsia-400/60', 'from-pink-300/70 via-purple-400/60 to-indigo-500/60'], capabilities: ['Фото-сеты', 'Stories', 'Reels'] },
  { id: 'rina-sport', displayName: 'Rina Sport', ageGroup: 'Adult 21+', city: 'Warsaw', languages: ['RU', 'EN', 'PL'], specialization: 'fitness', vibe: 'Энергичный фитнес-контент без провокационных тем.', bio: 'Взрослый персонаж (21+) для wellness и спортивных брендов. Подходит для безопасного SFW-контента.', strengths: ['Фитнес-контент', 'Рутина дня', 'Бренд-интеграции'], tags: ['fitness', 'wellness', 'routine'], access: 'trial', contentRating: 'SFW', previewImages: ['from-emerald-400/70 via-lime-400/60 to-slate-900', 'from-teal-500/60 via-emerald-500/60 to-cyan-600/60', 'from-lime-500/60 via-green-500/60 to-emerald-700/70'], capabilities: ['Фото-сеты', 'Stories', 'Reels'] },
  { id: 'katya-board', displayName: 'Katya Board', ageGroup: 'Adult 21+', city: 'London', languages: ['EN', 'RU'], specialization: 'business', vibe: 'Деловой стиль для экспертного и B2B-контента.', bio: 'Взрослый персонаж (21+) в business-направлении. Подходит для рубрик про карьеру и личный бренд.', strengths: ['Бизнес-лайфстайл', 'Экспертные рубрики', 'LinkedIn-стиль'], tags: ['business', 'expert', 'minimal'], access: 'trial', contentRating: 'SFW', previewImages: ['from-slate-400/70 via-zinc-500/70 to-slate-800/70', 'from-indigo-400/60 via-slate-500/60 to-zinc-800/70', 'from-slate-300/70 via-gray-500/70 to-slate-900/70'], capabilities: ['Фото-сеты', 'Stories', 'Сценарии'] },
  { id: 'maya-route', displayName: 'Maya Route', ageGroup: 'Adult 21+', city: 'Lisbon', languages: ['EN', 'PT', 'RU'], specialization: 'travel', vibe: 'Лёгкий travel-визуал и атмосферные городские сценарии.', bio: 'Взрослый персонаж (21+) для travel/hospitality проектов. SFW-подача и стабильный tone of voice.', strengths: ['Travel-гайды', 'Сторителлинг', 'Hotel/editorial'], tags: ['travel', 'coastal', 'lifestyle'], access: 'trial', contentRating: 'SFW', previewImages: ['from-cyan-300/70 via-sky-400/60 to-blue-700/70', 'from-emerald-300/60 via-cyan-400/60 to-sky-600/70', 'from-blue-300/60 via-cyan-400/60 to-teal-600/70'], capabilities: ['Фото-сеты', 'Stories', 'Reels'] },
  { id: 'mira-flare', displayName: 'Mira Flare', ageGroup: 'Adult 21+', city: 'Barcelona', languages: ['EN', 'ES', 'RU'], specialization: 'beauty', vibe: 'Яркая beauty-эстетика и промо-кампании.', bio: 'Взрослый персонаж (21+) для beauty и lifestyle контента, включая suggestive-концепции.', strengths: ['Промо-съёмка', 'Beauty-серии', 'Бренд-кампании'], tags: ['beauty', 'promo', 'editorial'], access: 'pro', contentRating: '18+', previewImages: ['from-amber-400/70 via-orange-500/70 to-rose-500/70', 'from-cyan-500/60 via-sky-500/60 to-indigo-700/60', 'from-orange-500/60 via-pink-500/50 to-purple-600/60'], capabilities: ['Фото-сеты', 'Stories', 'Reels', 'Сценарии'] },
  { id: 'eva-korr', displayName: 'Eva Korr', ageGroup: 'Adult 21+', city: 'Berlin', languages: ['EN', 'DE'], specialization: 'editorial', vibe: 'Смелый editorial-стиль для fashion и music брендов.', bio: 'Взрослый персонаж (21+) с альтернативным визуалом и акцентом на выразительный бренд-контент.', strengths: ['Editorial-стиль', 'Moodboard-сеты', 'Street-fashion'], tags: ['editorial', 'streetwear', 'neon'], access: 'pro', contentRating: '18+', previewImages: ['from-zinc-900 via-purple-800/70 to-pink-600/60', 'from-slate-900 via-fuchsia-700/60 to-indigo-600/70', 'from-purple-900/70 via-rose-700/60 to-zinc-950'], capabilities: ['Фото-сеты', 'Reels', 'Озвучка'] },
  { id: 'zara-iron', displayName: 'Zara Iron', ageGroup: 'Adult 21+', city: 'New York', languages: ['EN'], specialization: 'fitness', vibe: 'Urban fitness и спортивный fashion для активной аудитории.', bio: 'Взрослый персонаж (21+) для динамичных кампаний с сильной визуальной дисциплиной.', strengths: ['Фитнес-сеты', 'Короткие ролики', 'Спорт-fashion'], tags: ['fitness', 'urban', 'performance'], access: 'pro', contentRating: 'SFW', previewImages: ['from-red-500/70 via-orange-500/70 to-zinc-900/80', 'from-orange-500/60 via-amber-400/60 to-slate-800/80', 'from-rose-500/60 via-red-500/60 to-zinc-900/80'], capabilities: ['Фото-сеты', 'Stories', 'Reels'] },
  { id: 'nova-cos', displayName: 'Nova Cos', ageGroup: 'Adult 21+', city: 'Tokyo', languages: ['EN', 'JP'], specialization: 'cosplay', vibe: 'Character-driven образы и сезонные дропы.', bio: 'Взрослый персонаж (21+) для косплей и pop-culture направлений в premium-сегменте.', strengths: ['Косплей-образы', 'Сезонные кампании', 'Fan-контент'], tags: ['cosplay', 'character', 'campaign'], access: 'elite', contentRating: '18+', previewImages: ['from-cyan-400/70 via-blue-500/70 to-violet-600/70', 'from-violet-500/70 via-pink-500/70 to-orange-400/70', 'from-sky-500/70 via-indigo-500/70 to-fuchsia-500/70'], capabilities: ['Фото-сеты', 'Stories', 'Reels', 'Озвучка'] },
  { id: 'alina-velvet', displayName: 'Alina Velvet', ageGroup: 'Adult 21+', city: 'Dubai', languages: ['RU', 'EN'], specialization: 'luxury', vibe: 'Премиальный luxury-стиль и сложные fashion-сценарии.', bio: 'Взрослый персонаж (21+) для high-end брендов, визуала уровня campaign/editorial.', strengths: ['Luxury-кампании', 'Editorial-съёмка', 'Premium stories'], tags: ['luxury', 'fashion', 'premium'], access: 'elite', contentRating: '18+', previewImages: ['from-violet-500/60 via-fuchsia-500/60 to-slate-900', 'from-zinc-800 via-indigo-700/70 to-fuchsia-500/50', 'from-fuchsia-600/60 via-purple-600/60 to-zinc-900'], capabilities: ['Фото-сеты', 'Stories', 'Reels', 'Озвучка'] },
  { id: 'luna-boudoir', displayName: 'Luna Boudoir', ageGroup: 'Adult 21+', city: 'Milan', languages: ['IT', 'EN', 'RU'], specialization: 'voice/persona', vibe: 'Камерный стиль и персонализированные voice/persona сценарии.', bio: 'Взрослый персонаж (21+) для premium-брендов, где важна узнаваемая persona и авторский tone.', strengths: ['Voice persona', 'Имиджевые серии', 'Персональные сценарии'], tags: ['persona', 'premium', 'editorial'], access: 'elite', contentRating: '18+', previewImages: ['from-rose-400/70 via-fuchsia-400/60 to-zinc-900/80', 'from-purple-500/60 via-rose-400/60 to-amber-300/60', 'from-fuchsia-500/60 via-pink-500/60 to-slate-900/80'], capabilities: ['Фото-сеты', 'Stories', 'Reels'] },
];

export function getAvailableModelById(modelId: string) {
  return AVAILABLE_GIRLS.find((model) => model.id === modelId);
}
